Switch to use entware-ng dnscrypt-proxy to support platforms easier

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -32,14 +32,64 @@ case $(uname -m) in
     ;;
 esac
 
-if [ "`nvram get jffs2_format`" == "1" ]; then
-  echo -e "$ERROR JFFS partition is scheduled to be reformatted"
-  echo -e "$ERROR Please reboot to format or disable that setting and try again. Exiting..."
-  exit 1
-fi
-
 _quote() {
   echo $1 | sed 's/[]\/()$*.^|[]/\\&/g'
+}
+
+check_entware_installed () {
+  if [ -z "`which opkg`" ]; then
+    echo -e "$ERROR entware-ng is not installed"
+    echo -e "$ERROR Please make sure you have an ext2/3/4 file system usb drive connected and install entware-ng with entware-setup.sh"
+    echo -e "$ERROR or following this guide https://www.hqt.ro/how-to-install-new-generation-entware/"
+    echo -e "$ERROR then try this again. Exiting..."
+    exit 1
+  fi
+}
+
+check_jffs_enabled () {
+  if [ "`nvram get jffs2_format`" == "1" ]; then
+    echo -e "$ERROR JFFS partition is scheduled to be reformatted"
+    echo -e "$ERROR Please reboot to format or disable that setting and try again. Exiting..."
+    exit 1
+  fi
+
+  JFFS2_ENABLED=`nvram get jffs2_enable`
+  JFFS2_SCRIPTS=`nvram get jffs2_scripts`
+
+  if [ $JFFS2_ENABLED -ne 1 ] || [ $JFFS2_SCRIPTS -ne 1 ]; then
+    echo -e "$INFO JFFS custom scripts and configs are not enabled. Enabling them"
+    nvram set jffs2_enable=1
+    nvram set jffs2_scripts=1
+    nvram commit
+  else
+    echo -e "$INFO JFFS custom scripts and configs are already enabled"
+  fi
+}
+
+check_install_dnscrypt () {
+  opkg update
+  PKGS="`opkg list-installed`"
+  if [ -z "`echo $PKGS|grep nonroot`" ]; then
+    opkg install nonroot
+    if [ $? -ne 0 ]; then
+      echo -e "$ERROR Unable to install nonroot. Exiting..."
+      exit 1
+    fi
+  else
+    echo -e "$INFO nonroot already exists, do nothing"
+  fi
+  if [ -z "`echo $PKGS|grep dnscrypt-proxy`" ]; then
+    opkg install dnscrypt-proxy
+    if [ $? -ne 0 ]; then
+      echo -e "$ERROR Unable to install dnscrypt-proxy. Exiting..."
+      exit 1
+    fi
+    DNS_ENT="`cat /opt/etc/init.d/*dnscrypt*|grep ^ARGS=|awk 'NF>1{print $NF}'`"
+    DNS_ENT=${DNS_ENT%?}
+  else
+    echo -e "$INFO dnscrypt-proxy already exists, do nothing"
+  fi
+  chmod 000 /opt/etc/init.d/*dnscrypt*
 }
 
 del_between_magic () {
@@ -131,23 +181,9 @@ yesno_query () {
   esac
 }
 
-check_jffs_enabled () {
-  JFFS2_ENABLED=`nvram get jffs2_enable`
-  JFFS2_SCRIPTS=`nvram get jffs2_scripts`
-
-  if [ $JFFS2_ENABLED -ne 1 ] || [ $JFFS2_SCRIPTS -ne 1 ]; then
-    echo -e "$INFO JFFS custom scripts and configs are not enabled. Enabling them"
-    nvram set jffs2_enable=1
-    nvram set jffs2_scripts=1
-    nvram commit
-  else
-    echo -e "$INFO JFFS custom scripts and configs are already enabled"
-  fi
-}
-
 choose_dnscrypt_server () {
   if [ $1 -eq 1 ] && [ -z $2 ]; then
-    echo -e "$INFO Available DNS servers: "
+    [ -z "$DNS_ENT" ] && echo -e "$INFO Available DNS servers: "
     INDEX=0
     while read LINE; do
       if [ $INDEX -eq 0 ]; then
@@ -155,12 +191,20 @@ choose_dnscrypt_server () {
         continue
       fi
       SERVER="`echo $LINE|cut -d',' -f1,2,3|sed 's/,/: /'`"
-      echo -e "  $INDEX) $SERVER"
+      [ -z "$DNS_ENT" ] && echo -e "  $INDEX) $SERVER"
       SERVER="`echo $SERVER | cut -d':' -f1`"
       eval "ITEM$INDEX=$SERVER"
       INDEX=$((INDEX+1))
-    done < /jffs/dnscrypt/dnscrypt-resolvers.csv
-    echo -en "$INPUT Please choose DNS server\n$BOLD[1-`expr $INDEX - 1`]$NORM: "
+    done < /opt/share/dnscrypt-proxy/dnscrypt-resolvers.csv
+    if [ "$DNS_ENT" ]; then
+      echo -e "$INFO Use selected DNS server during dnscrypt-proxy installation"
+      write_conf DNS$1 "$DNS_ENT"
+      [ "`echo $DNS_ENT | grep cisco`" ] && CISCO_ENABLED=1
+      choose_dnscrypt_server 2
+      return
+    else
+      echo -en "$INPUT Please choose DNS server\n$BOLD[1-`expr $INDEX - 1`]$NORM: "
+    fi
   elif [ $1 -eq 2 ] && [ -z $2 ]; then
     echo -en "$INPUT Please choose 2nd DNS server or press n to skip\n$BOLD[1-`expr $INDEX - 1`/n]$NORM: "
   fi
@@ -214,6 +258,10 @@ inst_ip_update () {
 }
 
 inst_dnscrypt () {
+  check_jffs_enabled
+  check_entware_installed
+  check_install_dnscrypt
+
   local TARG=/jffs/dnscrypt
   mkdir -p $TARG
   if [ $? -ne 0 ]; then
@@ -221,13 +269,11 @@ inst_dnscrypt () {
     exit 1
   fi
 
-  download_file $TARG 644 https://raw.githubusercontent.com/jedisct1/dnscrypt-proxy/master/dnscrypt-resolvers.csv
-  download_file $TARG 755 $URL_GEN/dnsmasq-dnscrypt-reconfig $URL_GEN/dnscrypt-fw-rules $URL_GEN/dnscrypt-start $URL_ARCH/dnscrypt-proxy $URL_ARCH/haveged $URL_ARCH/nonroot
+  download_file $TARG 755 $URL_GEN/dnsmasq-dnscrypt-reconfig $URL_GEN/dnscrypt-fw-rules $URL_GEN/dnscrypt-start $URL_ARCH/haveged
 
   write_jffs_script /jffs/scripts/wan-start $TARG/dnscrypt-start
   write_jffs_script /jffs/scripts/dnsmasq.postconf $TARG/dnsmasq-dnscrypt-reconfig
 
-  check_jffs_enabled
   choose_dnscrypt_server 1
   [ "$CISCO_ENABLED" == "1" ] && yesno_query "Do you want to set up OpenDNS account ip update" "inst_ip_update 1" "inst_ip_update 0" || inst_ip_update 0
   yesno_query "Do you want to redirect all DNS resolutions on your network through dnscrypt?" "write_jffs_script /jffs/scripts/firewall-start $TARG/dnscrypt-fw-rules" "chmod 000 $TARG/dnscrypt-fw-rules"
@@ -236,4 +282,4 @@ inst_dnscrypt () {
   echo -e "$INFO Please reboot your router for the changes to take effect!"
 }
 
-yesno_query "Do you want to install dnscrypt-proxy to /jffs" inst_dnscrypt
+yesno_query "Do you want to install dnscrypt-proxy to /jffs" inst_dnscrypt "exit 0"
