Add log level setting Allow user to run dnscrypt-proxy configuration separately

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -158,8 +158,13 @@ inst_dnscrypt () {
   local DNSCRYPT_TAR=dnscrypt-proxy-${DNSCRYPT_ARCH}-${DNSCRYPT_VER}.tar.gz
   local RESOLVERS_URL_PREFIX="http://download.dnscrypt.info/resolvers-list/v2"
   local TARG=/jffs/dnscrypt
-  create_dir $TARG || end_op_message
+  create_dir $TARG
+  if [ $? -ne 0 ]; then
+    end_op_message
+    return 1
+  fi
 
+  download_file $TARG 755 $URL_GEN/manager $URL_ARCH/nonroot
   download_file $TARG 644 https://github.com/jedisct1/dnscrypt-proxy/releases/download/${DNSCRYPT_VER}/${DNSCRYPT_TAR} \
     $RESOLVERS_URL_PREFIX/public-resolvers.md \
     $RESOLVERS_URL_PREFIX/public-resolvers.md.minisig
@@ -173,15 +178,16 @@ inst_dnscrypt () {
   mv $TARG/$DNSCRYPT_ARCH_TAR/* $TARG
   rm -r $TARG/$DNSCRYPT_ARCH_TAR $TARG/$DNSCRYPT_TAR
   chmod 755 $TARG/dnscrypt-proxy
-  preset_dnscrypt_settings
-  choose_dnscrypt_server 1
 
-  download_file $TARG 755 $URL_GEN/manager $URL_ARCH/nonroot
   write_manager_script /jffs/scripts/dnsmasq.postconf dnsmasq
   write_manager_script /jffs/scripts/wan-start dnscrypt-start
-  [ "$CISCO_ENABLED" == "1" ] && yesno_query "Do you want to set up OpenDNS account ip update" "inst_ip_update 1" "inst_ip_update 0" || inst_ip_update 0
-  yesno_query "Do you want to redirect all DNS resolutions on your network through dnscrypt?" "write_manager_script /jffs/scripts/firewall-start fw-rules" "del_jffs_script /jffs/scripts/firewall-start fw-rules"
+  setup_dnscrypt
+  if [ $? -ne 0 ]; then
+    end_op_message
+    return 1
+  fi
 
+  echo -e "$INFO For dnscrypt-proxy version 2 to work reliably, a swap file is recommended"
   end_op_message 0
 }
 
@@ -342,17 +348,42 @@ inst_swap () {
   end_op_message 0
 }
 
-preset_dnscrypt_settings () {
-  local TARG=/jffs/dnscrypt/dnscrypt-proxy.toml
+read_input_num () {
+  echo -en "$INPUT $1, $BOLD[$2-$3]$NORM: "
+  read CHOSEN
+  if [ -z "`echo $CHOSEN | grep -E '^[0-9]+$'`" ]; then
+    echo -e "$ERROR Invalid character entered! Retrying..."
+    read_input_num $@
+    return
+  fi
+  if [ $CHOSEN -lt $2 ] || [ $CHOSEN -gt $3 ] ; then
+    echo -e "$ERROR Chosen DNS server number is not in range! Retrying..."
+    read_input_num $@
+    return
+  fi
+}
 
+setup_dnscrypt () {
+  local TARG=/jffs/dnscrypt/dnscrypt-proxy.toml
+  if [ ! -f $TARG ]; then
+    echo -e "$ERROR Unable to find $TARG. Aborting..."
+    return 1
+  fi
+  echo -e "$INFO Configuring dnscrypt-proxy..."
   toml_var_write $TARG listen_addresses "['127.0.0.1:65053']"
   toml_var_write $TARG require_nolog "false"
   toml_var_write $TARG require_nofilter "false"
   toml_var_write $TARG daemonize "true"
-  # toml_var_write $TARG log_level "4"
   toml_var_write $TARG use_syslog "true"
   toml_var_write $TARG cache "false"
   toml_var_write $TARG cert_ignore_timestamp "true"
+
+  read_input_num "Set log level, default is 2, 0 is the most verbose" 0 6
+  toml_var_write $TARG log_level "$CHOSEN"
+
+  choose_dnscrypt_server 1
+  [ "$CISCO_ENABLED" == "1" ] && yesno_query "Do you want to set up OpenDNS account ip update" "inst_ip_update 1" "inst_ip_update 0" || inst_ip_update 0
+  yesno_query "Do you want to redirect all DNS resolutions on your network through dnscrypt?" "write_manager_script /jffs/scripts/firewall-start fw-rules" "del_jffs_script /jffs/scripts/firewall-start fw-rules"
 }
 
 toml_array_clean () {
@@ -509,9 +540,10 @@ cleanup
 
 menu () {
   echo -e "$INFO Choose what you want to do:"
-  echo -e "  1) Install dnscrypt"
-  echo -e "  2) Install (P)RNG only"
-  echo -e "  3) Install swap file"
+  echo -e "  1) Install dnscrypt-proxy"
+  echo -e "  2) Configure dnscrypt-proxy"
+  echo -e "  3) Install (P)RNG"
+  echo -e "  4) Install swap file"
   echo -e "  q) Quit"
   echo -en "$INPUT Please enter the number designates your selection: $NORM"
   read CHOSEN
@@ -524,14 +556,19 @@ menu () {
       yesno_query "Do you want to install dnscrypt-proxy to /jffs" inst_dnscrypt "menu"
       ;;
     2)
+      echo -e "$INFO This operation allows you to configure dnscrypt-proxy"
+      echo
+      yesno_query "Do you want to proceed?" "setup_dnscrypt ; end_op_message 0" "menu"
+      ;;
+    3)
       echo -e "$INFO This operation will install a (P)RNG (<0.5MB)"
       echo -e "$INFO to jffs, no other data will be changed."
       echo -e "$INFO Also some start scripts will be installed/modified as required."
       echo
       yesno_query "Do you want to install (P)RNG to /jffs" inst_random "menu"
       ;;
-    3)
-      echo -e "$INFO For dnscrypt-proxy version 2 to work reliably, a swap file is recommended"
+    4)
+      echo -e "$INFO This operation will install a swap file for your device"
       echo -e "$INFO You need an external USB storage to host this file"
       echo
       yesno_query "Do you want to install a swap file (512MB on ext filesystem partition)?" check_swap "menu"
