Add back binaries for armv7 Use 2 install path: entware-ng for mips and own compiled bins for armv7

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -13,21 +13,24 @@ echo -e "$INFO Also some start scripts will be installed/modified as required."
 echo
 
 URL_GEN=https://raw.githubusercontent.com/thuantran/dnscrypt-asuswrt-installer/master/gen
+URL_ARCH=https://github.com/thuantran/dnscrypt-asuswrt-installer/raw/master
 
-_install_pkg () {
-  PKGS="`opkg list-installed`"
-  if [ -z "`echo $PKGS|grep \"$1 \"`" ]; then
-    opkg install $1
-    if [ $? -ne 0 ]; then
-      echo -e "$ERROR Unable to install $1. Exiting..."
-      exit 1
-    fi
-    return 1
-  else
-    echo -e "$INFO $1 already exists, do nothing"
-  fi
-  return 0
-}
+case $(uname -m) in
+  armv7l)
+    URL_ARCH=$URL_ARCH/armv7
+    echo -e "$INFO Detected ARM architecture."
+    echo
+    ;;
+  mips)
+    URL_ARCH=$URL_ARCH/mips
+    echo -e "$INFO Detected MIPSEL architecture."
+    echo
+    ;;
+  *)
+    echo "This is unsupported platform, sorry."
+    exit 1
+    ;;
+esac
 
 _quote() {
   echo $1 | sed 's/[]\/()$*.^|[]/\\&/g'
@@ -61,107 +64,6 @@ check_jffs_enabled () {
   else
     echo -e "$INFO JFFS custom scripts and configs are already enabled"
   fi
-}
-
-check_install_dnscrypt () {
-  opkg update
-  opkg upgrade
-  _install_pkg rng-tools
-  _install_pkg nonroot
-  _install_pkg dnscrypt-proxy
-  if [ $? -eq 1 ]; then
-    DNS_ENT="`cat /opt/etc/init.d/*dnscrypt*|grep ^ARGS=|awk 'NF>1{print $NF}'`"
-    DNS_ENT=${DNS_ENT%?}
-  fi
-}
-
-del_between_magic () {
-  local TARG=$1
-  MAGIC=$2
-  BOUNDS=`grep -n -F "$MAGIC" $TARG|cut -d':' -f1|tr '\n' ','`
-  if [ "$BOUNDS" ]; then
-    sed -i "${BOUNDS%,}d" $TARG
-  fi
-}
-
-download_file () {
-  cd "$1"
-  shift
-  PERM="$1"
-  shift
-
-  for URL in "$@"; do
-    FILENAME="`basename $URL`"
-    MD5SUM_OLD="`[ -f $FILENAME ] && md5sum $FILENAME|cut -d' ' -f1`"
-    MD5SUM_CURR="`curl -L -k -s \"${URL}.md5sum\"`"
-    if [ "$MD5SUM_CURR" ==  "$MD5SUM_OLD" ]; then
-      echo -e "$INFO $FILENAME is up to date. Skipping..."
-    else
-      echo -e "$INFO Downloading $FILENAME"
-      curl -L -k -s -O "$URL" && chmod $PERM $FILENAME
-    fi
-  done
-}
-
-write_conf () {
-  local TARG=/jffs/dnscrypt/.config
-  KEY="$1"
-  VALUE="$2"
-  [ -f /jffs/dnscrypt/.opendns-auth ] && mv /jffs/dnscrypt/.opendns-auth $TARG && chmod 644 $TARG
-  if [ ! -f $TARG ]; then
-    touch $TARG && chmod 644 $TARG
-  fi
-  if [ "`grep $KEY $TARG`" ]; then
-    VALUE=$(_quote $2)
-    sed -i "/^$KEY=/s/=.*/=$VALUE/" $TARG
-  else
-    echo "$KEY=$VALUE" >> $TARG
-  fi
-}
-
-write_jffs_script () {
-  local TARG=$1
-  FILENAME="`basename \"$TARG\"`"
-  COMMAND=$2
-
-  if [ ! -f $TARG ]; then
-    echo -e "$INFO Creating $FILENAME file"
-    echo "#!/bin/sh" > $TARG
-  fi
-  chmod 755 $TARG $COMMAND
-  del_between_magic $TARG dnscrypt-asuswrt-installer
-
-  if [ `grep -c -F "[ -x $COMMAND ] && $COMMAND" $TARG` -gt 0 ]; then
-    echo -e "$INFO $FILENAME file already configured"
-  else
-    echo -e "$INFO Configure $FILENAME file for dnscrypt"
-    if [ "`grep \"^$COMMAND\" $TARG`" ]; then
-      sed -i "s~^$COMMAND~[ -x $COMMAND ] \&\& $COMMAND~" $TARG
-    else
-      echo "" >> $TARG
-      echo "[ -x $COMMAND ] && $COMMAND" >> $TARG
-    fi
-  fi
-}
-
-yesno_query () {
-  QUERY=$1
-  YES_FUNC=$2
-  NO_FUNC=$3
-  echo -en "$INPUT $QUERY $BOLD[y/n]$NORM: "
-  read YESNO
-  case $YESNO in
-    y|Y)
-      eval $YES_FUNC
-      ;;
-    n|N)
-      eval $NO_FUNC
-      ;;
-    *)
-      echo -e "$ERROR Invalid input!"
-      yesno_query "$@"
-      ;;
-  esac
 }
 
 choose_dnscrypt_server () {
@@ -219,6 +121,46 @@ choose_dnscrypt_server () {
   [ $1 -eq 1 ] && choose_dnscrypt_server 2
 }
 
+del_between_magic () {
+  local TARG=$1
+  MAGIC=$2
+  BOUNDS=`grep -n -F "$MAGIC" $TARG|cut -d':' -f1|tr '\n' ','`
+  if [ "$BOUNDS" ]; then
+    sed -i "${BOUNDS%,}d" $TARG
+  fi
+}
+
+download_file () {
+  cd "$1"
+  shift
+  PERM="$1"
+  shift
+
+  for URL in "$@"; do
+    FILENAME="`basename $URL`"
+    MD5SUM_OLD="`[ -f $FILENAME ] && md5sum $FILENAME|cut -d' ' -f1`"
+    MD5SUM_CURR="`curl -L -k -s \"${URL}.md5sum\"`"
+    if [ "$MD5SUM_CURR" ==  "$MD5SUM_OLD" ]; then
+      echo -e "$INFO $FILENAME is up to date. Skipping..."
+    else
+      echo -e "$INFO Downloading $FILENAME"
+      curl -L -k -s -O "$URL" && chmod $PERM $FILENAME
+    fi
+  done
+}
+
+inst_entware_dnscrypt () {
+  opkg update
+  opkg upgrade
+  inst_pkg rng-tools
+  inst_pkg nonroot
+  inst_pkg dnscrypt-proxy
+  if [ $? -eq 1 ]; then
+    DNS_ENT="`cat /opt/etc/init.d/*dnscrypt*|grep ^ARGS=|awk 'NF>1{print $NF}'`"
+    DNS_ENT=${DNS_ENT%?}
+  fi
+}
+
 inst_ip_update () {
   if [ "$1" -eq 0 ]; then
     write_conf OPENDNS_USER ""
@@ -240,10 +182,114 @@ inst_ip_update () {
   write_conf OPENDNS_PASSWORD "\"$PW1\""
 }
 
-inst_dnscrypt () {
+inst_pkg () {
+  PKGS="`opkg list-installed`"
+  if [ -z "`echo $PKGS|grep \"$1 \"`" ]; then
+    opkg install $1
+    if [ $? -ne 0 ]; then
+      echo -e "$ERROR Unable to install $1. Exiting..."
+      exit 1
+    fi
+    return 1
+  else
+    echo -e "$INFO $1 already exists, do nothing"
+  fi
+  return 0
+}
+
+inst_random () {
+  local TARG=/jffs/dnscrypt
+  if [ -z $1 ]; then
+    echo -e "$INFO Available random number generator providers:"
+    echo -e "  1) HAVEGED (Preferred if you do not have a HW RNG)"
+    echo -e "  2) RNGD (Preferred if you have a HW RNG)"
+  fi
+  echo -en "$INPUT Please enter the number designates your selection$NORM: "
+  read CHOSEN
+  case $CHOSEN in
+    1)
+      download_file $TARG 755 $URL_ARCH/haveged
+      write_conf RAN_PRV haveged
+      ;;
+    2)
+      download_file $TARG 755 $URL_ARCH/rngd
+      write_conf RAN_PRV rngd
+      inst_truerng
+      ;;
+    *)
+      echo -e "$ERROR Invalid character entered! Retrying..."
+      inst_random x
+      ;;
+  esac
+}
+
+inst_truerng () {
+  write_conf RNG_DEV "/dev/urandom"
+}
+
+yesno_query () {
+  QUERY=$1
+  YES_FUNC=$2
+  NO_FUNC=$3
+  echo -en "$INPUT $QUERY $BOLD[y/n]$NORM: "
+  read YESNO
+  case $YESNO in
+    y|Y)
+      eval $YES_FUNC
+      ;;
+    n|N)
+      eval $NO_FUNC
+      ;;
+    *)
+      echo -e "$ERROR Invalid input!"
+      yesno_query "$@"
+      ;;
+  esac
+}
+
+write_conf () {
+  local TARG=/jffs/dnscrypt/.config
+  KEY="$1"
+  VALUE="$2"
+  [ -f /jffs/dnscrypt/.opendns-auth ] && mv /jffs/dnscrypt/.opendns-auth $TARG && chmod 644 $TARG
+  if [ ! -f $TARG ]; then
+    touch $TARG && chmod 644 $TARG
+  fi
+  if [ "`grep $KEY $TARG`" ]; then
+    VALUE=$(_quote $2)
+    sed -i "/^$KEY=/s/=.*/=$VALUE/" $TARG
+  else
+    echo "$KEY=$VALUE" >> $TARG
+  fi
+}
+
+write_jffs_script () {
+  local TARG=$1
+  FILENAME="`basename \"$TARG\"`"
+  COMMAND=$2
+
+  if [ ! -f $TARG ]; then
+    echo -e "$INFO Creating $FILENAME file"
+    echo "#!/bin/sh" > $TARG
+  fi
+  chmod 755 $TARG $COMMAND
+  del_between_magic $TARG dnscrypt-asuswrt-installer
+
+  if [ `grep -c -F "[ -x $COMMAND ] && $COMMAND" $TARG` -gt 0 ]; then
+    echo -e "$INFO $FILENAME file already configured"
+  else
+    echo -e "$INFO Configure $FILENAME file for dnscrypt"
+    if [ "`grep \"^$COMMAND\" $TARG`" ]; then
+      sed -i "s~^$COMMAND~[ -x $COMMAND ] \&\& $COMMAND~" $TARG
+    else
+      echo "" >> $TARG
+      echo "[ -x $COMMAND ] && $COMMAND" >> $TARG
+    fi
+  fi
+}
+
+main () {
   check_jffs_enabled
-  check_entware_installed
-  check_install_dnscrypt
 
   local TARG=/jffs/dnscrypt
   mkdir -p $TARG
@@ -252,11 +298,25 @@ inst_dnscrypt () {
     exit 1
   fi
 
-  download_file $TARG 755 $URL_GEN/dnsmasq-dnscrypt-reconfig $URL_GEN/dnscrypt-fw-rules $URL_GEN/dnscrypt-start
-  rm -rf $TARG/dnscrypt-proxy $TARG/nonroot $TARG/haveged
+  download_file $TARG 755 $URL_GEN/dnsmasq-dnscrypt-reconfig $URL_GEN/dnscrypt-fw-rules $URL_ARCH/dnscrypt-start
+  case $(uname -m) in
+    armv7l)
+      download_file $TARG 644 https://raw.githubusercontent.com/jedisct1/dnscrypt-proxy/master/dnscrypt-resolvers.csv
+      download_file $TARG 755 $URL_ARCH/nonroot $URL_ARCH/dnscrypt-proxy
+      inst_random
+      ;;
+    mips)
+      rm -rf $TARG/dnscrypt-proxy $TARG/nonroot $TARG/haveged
+      check_entware_installed
+      inst_entware_dnscrypt
+      write_conf RAN_PRV rngd
+      inst_truerng
+      ;;
+  esac
 
-  write_jffs_script /jffs/scripts/wan-start $TARG/dnscrypt-start
   write_jffs_script /jffs/scripts/dnsmasq.postconf $TARG/dnsmasq-dnscrypt-reconfig
+  write_jffs_script /jffs/scripts/init-start $TARG/random-start
+  write_jffs_script /jffs/scripts/wan-start $TARG/dnscrypt-start
 
   choose_dnscrypt_server 1
   [ "$CISCO_ENABLED" == "1" ] && yesno_query "Do you want to set up OpenDNS account ip update" "inst_ip_update 1" "inst_ip_update 0" || inst_ip_update 0
@@ -266,4 +326,4 @@ inst_dnscrypt () {
   echo -e "$INFO Please reboot your router for the changes to take effect!"
 }
 
-yesno_query "Do you want to install dnscrypt-proxy to /jffs" inst_dnscrypt "exit 0"
+yesno_query "Do you want to install dnscrypt-proxy to /jffs" main "exit 0"
