Update installer

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -50,6 +50,21 @@ backup_restore () {
   if [ -f $BASE_DIR/backup_dnscrypt.tar.gz ] && [ "$1" == "RESTORE" ]; then
     echo -e "$INFO Please wait a moment."
     tar -xvzpf /jffs/backup_dnscrypt.tar.gz >/dev/null 2>&1
+    local NW_STATE
+    local RES_STATE
+    ping 1.1.1.1 -c1 -W2 >/dev/null 2>&1
+    NW_STATE=$?
+    nslookup google.com >/dev/null 2>&1
+    RES_STATE=$?
+    if [ $NW_STATE -eq 0 ] && [ $RES_STATE -ne 0 ]; then
+      echo -e "$ERROR No internet- Skipping the updating for Server/Relay Files."
+    else
+      download_file $TARG_DIR 644 $RESOLVERS_URL_PREFIX/public-resolvers.md \
+        $RESOLVERS_URL_PREFIX/public-resolvers.md.minisig \
+        $RESOLVERS_URL_PREFIX/relays.md \
+        $RESOLVERS_URL_PREFIX/relays.md.minisig
+      chown nobody:nobody $TARG_DIR/public-resolvers.md $TARG_DIR/public-resolvers.md.minisig $TARG_DIR/relays.md $TARG_DIR/relays.md.minisig
+    fi 
     del_jffs_script /jffs/scripts/wan-start dnscrypt-start
     del_jffs_script /jffs/scripts/openvpn-event
     del_jffs_script /jffs/scripts/firewall-start
