Update installer

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -1584,10 +1584,10 @@ clear
 sed -n '2,24p' "$0"
 
 case $ROUTER_MODEL in
-  RT-AX56U|RT-AX58U|RT-AX3000)
-    echo -e "$INFO Detected $ROUTER_MODEL router."
-    CONDITIONAL_ARCH=TRUE
-    ;;
+  #RT-AX56U|RT-AX58U|RT-AX3000)
+  #  echo -e "$INFO Detected $ROUTER_MODEL router."
+  #  CONDITIONAL_ARCH=TRUE
+  #  ;;
   *)
     echo -e "$INFO Detected $ROUTER_MODEL router."
     ;;
@@ -1603,42 +1603,36 @@ case $ROUTER_OS in
     exit 1
     ;;
 esac
-if [ "$CONDITIONAL_ARCH" = "TRUE" ]; then
-  ROUTER_ARCH=arm
-  URL_ARCH=$URL_ARCH/armv7
-  DNSCRYPT_ARCH=${ROUTER_OS}_${ROUTER_ARCH}
-  DNSCRYPT_ARCH_TAR=${ROUTER_OS}-${ROUTER_ARCH}
-  echo -e "$INFO Detected ARMv7 architecture."
-else
-  case $ROUTER_ARCH in
-    aarch64|arm64)
-      ROUTER_ARCH=arm64
-      URL_ARCH=$URL_ARCH/armv8
-      DNSCRYPT_ARCH=${ROUTER_OS}_${ROUTER_ARCH}
-      DNSCRYPT_ARCH_TAR=${ROUTER_OS}-${ROUTER_ARCH}
-      echo -e "$INFO Detected ARMv8 architecture."
-      ;;
-    armv7l)
-      ROUTER_ARCH=arm
-      URL_ARCH=$URL_ARCH/armv7
-      DNSCRYPT_ARCH=${ROUTER_OS}_${ROUTER_ARCH}
-      DNSCRYPT_ARCH_TAR=${ROUTER_OS}-${ROUTER_ARCH}
-      echo -e "$INFO Detected ARMv7 architecture."
-      ;;
-    # mips)
-      # URL_ARCH=$URL_ARCH/mips
-      # DNSCRYPT_ARCH=linux_mipsle
-      # DNSCRYPT_ARCH_TAR=linux-mipsle
-      # echo -e "$INFO Detected MIPSEL architecture."
-      # echo -e "$WARNING FOR TESTING ONLY, MIGHT NOT WORK AT ALL"
-      # echo -e "$WARNING USE AT YOUR OWN RISK"
-      # ;;
-    *)
-      echo -e "$ERROR This is an unsupported architecture, sorry."
-      exit 1
-      ;;
-  esac
-fi
+
+case $ROUTER_ARCH in    
+  aarch64|arm64)
+    ROUTER_ARCH=arm64
+    URL_ARCH=$URL_ARCH/armv8
+    DNSCRYPT_ARCH=${ROUTER_OS}_${ROUTER_ARCH}
+    DNSCRYPT_ARCH_TAR=${ROUTER_OS}-${ROUTER_ARCH}
+    echo -e "$INFO Detected ARMv8 architecture."
+    ;;
+  armv7l)
+    ROUTER_ARCH=arm
+    URL_ARCH=$URL_ARCH/armv7
+    DNSCRYPT_ARCH=${ROUTER_OS}_${ROUTER_ARCH}
+    DNSCRYPT_ARCH_TAR=${ROUTER_OS}-${ROUTER_ARCH}
+    echo -e "$INFO Detected ARMv7 architecture."
+    ;;
+  # mips)
+   # URL_ARCH=$URL_ARCH/mips
+   # DNSCRYPT_ARCH=linux_mipsle
+   # DNSCRYPT_ARCH_TAR=linux-mipsle
+   # echo -e "$INFO Detected MIPSEL architecture."
+   # echo -e "$WARNING FOR TESTING ONLY, MIGHT NOT WORK AT ALL"
+   # echo -e "$WARNING USE AT YOUR OWN RISK"
+   # ;;
+  *)
+    echo -e "$ERROR This is an unsupported architecture, sorry."
+    exit 1
+    ;;
+esac
+
 
 check_jffs_enabled
 check_dns_environment
