--Still dev code-- Refactor code Make install swap a separate feature Allow running multiple operations per run

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -32,14 +32,13 @@ check_jffs_enabled () {
 }
 
 check_swap () {
-  echo 1
   SWAP_SIZE=`cat /proc/meminfo | grep SwapTotal | awk '{print $2}'`
-  [ $SWAP_SIZE -gt 0 ] && return 0
+  if [ $SWAP_SIZE -gt 0 ]; then
+    echo -e "$INFO Swap file is already setup. Exiting..."
+    return 0
+  fi
 
-  echo -e "$INFO For dnscrypt-proxy version 2 to work reliably, a swap file is recommended"
-  echo -e "$INFO You need an external storage to host this file"
-  echo
-  yesno_query "Do you want to install a swap file (512MB on ext filesystem partition)?" inst_swap
+  inst_swap
 }
 
 choose_dnscrypt_server () {
@@ -153,18 +152,22 @@ download_file () {
 }
 
 inst_dnscrypt () {
+
   echo inst_dnscrypt
   # local TARG=/jffs/dnscrypt
   # create_dir $TARG
 
+  # local TMP=/root
+  # download_file $TMP 644 
+  
   # download_file $TARG 644 https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v1/dnscrypt-resolvers.csv
   # download_file $TARG 755 $URL_GEN/manager $URL_ARCH/dnscrypt-proxy $URL_ARCH/nonroot
 
-  # write_jffs_script /jffs/scripts/dnsmasq.postconf $TARG/manager dnsmasq
-  # write_jffs_script /jffs/scripts/wan-start $TARG/manager dnscrypt-start
+  # write_manager_script /jffs/scripts/dnsmasq.postconf dnsmasq
+  # write_manager_script /jffs/scripts/wan-start dnscrypt-start
   # choose_dnscrypt_server 1
   # [ "$CISCO_ENABLED" == "1" ] && yesno_query "Do you want to set up OpenDNS account ip update" "inst_ip_update 1" "inst_ip_update 0" || inst_ip_update 0
-  # yesno_query "Do you want to redirect all DNS resolutions on your network through dnscrypt?" "write_jffs_script /jffs/scripts/firewall-start $TARG/manager fw-rules" "del_jffs_script /jffs/scripts/firewall-start fw-rules"
+  # yesno_query "Do you want to redirect all DNS resolutions on your network through dnscrypt?" "write_manager_script /jffs/scripts/firewall-start fw-rules" "del_jffs_script /jffs/scripts/firewall-start fw-rules"
 
   # echo -e "$INFO Install a (P)RNG for better cryptographic operations"
   # inst_random
@@ -223,8 +226,8 @@ inst_random () {
       ;;
   esac
 
-  write_jffs_script /jffs/scripts/init-start $TARG/manager init-start
-  write_jffs_script /jffs/scripts/services-stop $TARG/manager services-stop
+  write_manager_script /jffs/scripts/init-start init-start
+  write_manager_script /jffs/scripts/services-stop services-stop
 }
 
 inst_ran_dev () {
@@ -259,6 +262,8 @@ inst_ran_dev () {
 }
 
 inst_swap () {
+  local PARTITIONS
+
   SWAP_SIZE=524288
   USB_COUNT=`find /tmp/mnt/ -maxdepth 1 -type d|wc -l`
   if [ $USB_COUNT -le 1 ]; then
@@ -277,7 +282,8 @@ inst_swap () {
   done
 
   if [ -z SWAP_OK ]; then
-    echo -e "$ERROR No suitable external USB storage found\nPlease connect a USB storage with ext filesystem with enough free space"
+    echo -e "$ERROR No suitable external USB storage found"
+    echo -e "$ERROR Please connect a USB storage with ext filesystem with enough free space"
     exit 1
   fi
 
@@ -295,10 +301,25 @@ inst_swap () {
     inst_swap
     return
   fi
+  if [ $CHOSEN -lt 1 ] || [ $CHOSEN -gt `expr $INDEX - 1` ] ; then
+    echo -e "$ERROR Chosen partition number is not in range! Retrying..."
+    inst_swap
+    return
+  fi
 
+  unset MOUNT
   eval MOUNT="\$ITEM$CHOSEN"
+  if  [ -z $MOUNT ]; then
+    echo -e "$ERROR Unable to set partition to store swap file"
+    exit 1
+  fi
+  echo -e "$INFO Please wait..."
   dd if=/dev/zero of=$MOUNT/swap bs=1024 count=$SWAP_SIZE
   mkswap $MOUNT/swap
+
+  write_command_script /jffs/scripts/post-mount '[ -f $1/swap ] && swapon $1/swap'
+  write_command_script /jffs/scripts/unmount '[ -f $1/swap ] && swapoff $1/swap'
+  echo
 }
 
 yesno_query () {
@@ -337,11 +358,30 @@ write_conf () {
   fi
 }
 
-write_jffs_script () {
+write_command_script () {
   local TARG=$1
+  local COMMAND=$2
   FILENAME="`basename \"$TARG\"`"
-  COMMAND=$2
-  OP=$3
+
+  if [ ! -f $TARG ]; then
+    echo -e "$INFO Creating $FILENAME file"
+    echo "#!/bin/sh" > $TARG
+  fi
+  chmod 755 $TARG
+
+  if [ `grep -c -F "$COMMAND" $TARG` -gt 0 ]; then
+    echo -e "$INFO $FILENAME file already configured"
+  else
+    echo -e "$INFO Configure $FILENAME file"
+    echo "$COMMAND" >> $TARG
+  fi
+}
+
+write_manager_script () {
+  local TARG=$1
+  local OP=$2
+  FILENAME="`basename \"$TARG\"`"
+  COMMAND=/jffs/dnscrypt/manager
 
   if [ ! -f $TARG ]; then
     echo -e "$INFO Creating $FILENAME file"
@@ -386,31 +426,47 @@ esac
 check_jffs_enabled
 cleanup
 
-echo -e "$INFO Choose what you want to do:"
-echo -e "  1) Install dnscrypt and (P)RNG"
-echo -e "  2) Install (P)RNG only"
-echo -en "$INPUT Please enter the number designates your selection or any other key to exit$NORM: "
-read CHOSEN
-case $CHOSEN in
-  1)
-    check_swap
-    echo -e "$INFO This operation will install dnscrypt-proxy and related files (<6MB)"
-    echo -e "$INFO to jffs, no other data will be changed."
-    echo -e "$INFO Also some start scripts will be installed/modified as required."
-    echo
-    yesno_query "Do you want to install dnscrypt-proxy to /jffs" inst_dnscrypt "exit 0"
-    ;;
-  2)
-    echo -e "$INFO This operation will install a (P)RNG (<0.5MB)"
-    echo -e "$INFO to jffs, no other data will be changed."
-    echo -e "$INFO Also some start scripts will be installed/modified as required."
-    echo
-    yesno_query "Do you want to install (P)RNG to /jffs" inst_random "exit 0"
-    ;;
-  *)
-    echo -e "$ERROR Invalid character entered! Exiting..."
-    exit 1
-    ;;
-esac
-echo -e "$INFO Setup completed!"
-echo -e "$INFO Please reboot your router for the changes to take effect!"
+menu () {
+  echo -e "$INFO Choose what you want to do:"
+  echo -e "  1) Install dnscrypt and (P)RNG"
+  echo -e "  2) Install (P)RNG only"
+  echo -e "  3) Install swap file"
+  echo -e "  q) Quit"
+  echo -en "$INPUT Please enter the number designates your selection or any other key to exit$NORM: "
+  read CHOSEN
+  case $CHOSEN in
+    1)
+      echo -e "$INFO This operation will install dnscrypt-proxy and related files (<6MB)"
+      echo -e "$INFO to jffs, no other data will be changed."
+      echo -e "$INFO Also some start scripts will be installed/modified as required."
+      echo
+      yesno_query "Do you want to install dnscrypt-proxy to /jffs" inst_dnscrypt "menu"
+      menu
+      ;;
+    2)
+      echo -e "$INFO This operation will install a (P)RNG (<0.5MB)"
+      echo -e "$INFO to jffs, no other data will be changed."
+      echo -e "$INFO Also some start scripts will be installed/modified as required."
+      echo
+      yesno_query "Do you want to install (P)RNG to /jffs" inst_random "menu"
+      menu
+      ;;
+    3)
+      echo -e "$INFO For dnscrypt-proxy version 2 to work reliably, a swap file is recommended"
+      echo -e "$INFO You need an external USB storage to host this file"
+      echo
+      yesno_query "Do you want to install a swap file (512MB on ext filesystem partition)?" check_swap "menu"
+      menu
+      ;;
+    q|Q)
+      echo -e "$INFO Please reboot your router if you have made any change!"
+      exit 0
+      ;;
+    *)
+      echo -e "$ERROR Invalid character entered! Exiting..."
+      menu
+      ;;
+  esac
+}
+
+menu
