Add hardware rng support for TrueRNG (tested), TrueRNGpro, OneRNG, EntropyKey through rngd

diff --git a/gen/init-start b/gen/init-start
--- a/gen/init-start
+++ b/gen/init-start
@@ -4,11 +4,27 @@
 
 [ -f /jffs/dnscrypt/.config ] && . /jffs/dnscrypt/.config
 
+init_hwrng () {
+  modprobe cdc_acm
+  COUNT=0
+  while [ ! -c $RNG_DEV ]; do
+    if [ $COUNT -gt 120 ]; then
+      logger "ERROR: Unable to find HWRNG device. Aborting..."
+      exit 1
+    fi
+    COUNT=$((COUNT+1))
+    sleep 1
+  done
+  /jffs/dnscrypt/stty raw -echo -ixoff -F $RNG_DEV speed 115200
+  /jffs/dnscrypt/rngd -r $RNG_DEV
+  [ $? -eq 0 ] && logger "rngd: Started for $RNG_DEV"
+}
+
 case $RAN_PRV in
   haveged)
     /jffs/dnscrypt/haveged -w1024 -v1
     ;;
   rngd)
-    /jffs/dnscrypt/rngd -r $RNG_DEV
+    init_hwrng &
     ;;
 esac
